import traceback

from client.queries.updateCheck import UpdateCheck
from client.queries.baseCheck import InitiationQuery

if __name__ == '__main__':
    query_name1 = 'init_apkeep'
    network_name = 'forwarding-change-validation'
    snapshot_name = 'base'
    # make sure that parsed config files and data plane (fibs) hava been generated by batfish
    initQuery = InitiationQuery(query_name1, network_name, snapshot_name)
    try:
        initQuery.resolve()
        query_name2 = 'detect_loops'

        # update_rules path (Diffs of fibs) is generated by Diff.py

        update_rules = '/home/yuhao/workplace/batfish/containers/bda171ea-d22a-4675-9fa8-149f74dbf153/snapshots' \
                       '/36123a00-22da-4b8f-b3cd-f70ef86c7f2e/output/APKeep/init/batch_updates'

        query = UpdateCheck(query_name2, update_rules)
        answer = query.resolve()
        # print(answer.wrapper())
    except RuntimeError as e:
        traceback.print_exc()
